type ProvinceData = {
    id: number;
    Province: string;
  };
  
  const Province: ProvinceData[] = [
    { id: 1, Province: 'กระบี่' },
    { id: 2, Province: 'กรุงเทพมหานคร' },
    { id: 3, Province: 'กาญจนบุรี' },
    { id: 4, Province: 'กาฬสินธุ์' },
    { id: 5, Province: 'กำแพงเพชร' },
    { id: 6, Province: 'ขอนแก่น' },
    { id: 7, Province: 'จันทบุรี' },
    { id: 8, Province: 'ฉะเชิงเทรา' },
    { id: 9, Province: 'ชลบุรี' },
    { id: 10, Province: 'ชัยนาท' },
    { id: 11, Province: 'ชัยภูมิ' },
    { id: 12, Province: 'ชุมพร' },
    { id: 13, Province: 'เชียงราย' },
    { id: 14, Province: 'เชียงใหม่' },
    { id: 15, Province: 'ตรัง' },
    { id: 16, Province: 'ตราด' },
    { id: 17, Province: 'ตาก' },
    { id: 18, Province: 'นครนายก' },
    { id: 19, Province: 'นครปฐม' },
    { id: 20, Province: 'นครพนม' },
    { id: 21, Province: 'นครราชสีมา' },
    { id: 22, Province: 'นครศรีธรรมราช' },
    { id: 23, Province: 'นครสวรรค์' },
    { id: 24, Province: 'นนทบุรี' },
    { id: 25, Province: 'นราธิวาส' },
    { id: 26, Province: 'น่าน' },
    { id: 27, Province: 'บึงกาฬ' },
    { id: 28, Province: 'บุรีรัมย์' },
    { id: 29, Province: 'ปทุมธานี' },
    { id: 30, Province: 'ประจวบคีรีขันธ์' },
    { id: 31, Province: 'ปราจีนบุรี' },
    { id: 32, Province: 'ปัตตานี' },
    { id: 33, Province: 'พระนครศรีอยุธยา' },
    { id: 34, Province: 'พะเยา' },
    { id: 35, Province: 'พังงา' },
    { id: 36, Province: 'พัทลุง' },
    { id: 37, Province: 'พิจิตร' },
    { id: 38, Province: 'พิษณุโลก' },
    { id: 39, Province: 'เพชรบุรี' },
    { id: 40, Province: 'เพชรบูรณ์' },
    { id: 41, Province: 'แพร่' },
    { id: 42, Province: 'ภูเก็ต' },
    { id: 43, Province: 'มหาสารคาม' },
    { id: 44, Province: 'มุกดาหาร' },
    { id: 45, Province: 'แม่ฮ่องสอน' },
    { id: 46, Province: 'ยโสธร' },
    { id: 47, Province: 'ยะลา' },
    { id: 48, Province: 'ร้อยเอ็ด' },
    { id: 49, Province: 'ระนอง' },
    { id: 50, Province: 'ระยอง' },
    { id: 51, Province: 'ราชบุรี' },
    { id: 52, Province: 'ลพบุรี' },
    { id: 53, Province: 'ลำปาง' },
    { id: 54, Province: 'ลำพูน' },
    { id: 55, Province: 'เลย' },
    { id: 56, Province: 'ศรีสะเกษ' },
    { id: 57, Province: 'สกลนคร' },
    { id: 58, Province: 'สงขลา' },
    { id: 59, Province: 'สตูล' },
    { id: 60, Province: 'สมุทรปราการ' },
    { id: 61, Province: 'สมุทรสงคราม' },
    { id: 62, Province: 'สมุทรสาคร' },
    { id: 63, Province: 'สระแก้ว' },
    { id: 64, Province: 'สระบุรี' },
    { id: 65, Province: 'สิงห์บุรี' },
    { id: 66, Province: 'สุโขทัย' },
    { id: 67, Province: 'สุพรรณบุรี' },
    { id: 68, Province: 'สุราษฎร์ธานี' },
    { id: 69, Province: 'สุรินทร์' },
    { id: 70, Province: 'หนองคาย' },
    { id: 71, Province: 'หนองบัวลำภู' },
    { id: 72, Province: 'อ่างทอง' },
    { id: 73, Province: 'อำนาจเจริญ' },
    { id: 74, Province: 'อุดรธานี' },
    { id: 75, Province: 'อุตรดิตถ์' },
    { id: 76, Province: 'อุทัยธานี' },
    { id: 77, Province: 'อุบลราชธานี' }
  ];
  
  export default Province;